spring.application.name: cloudland-gemini-spring-ai
spring:
  ai:
    vertex:
      ai:
        gemini:
          project-id: ${GCP_PROJECT_ID:persian-java-talk}
          location: ${REGION:us-central1}
#          chat:
#            options:
#              functions: currentWeather

weather:
  api-key: ${WEATHER_API_KEY}
  api-url: http://api.weatherapi.com/v1